language: generic
sudo: required

services:
  - docker

before_install:
  - docker build -t edwardyhuang/docker-react -f Dockerfile.dev .

script:
  - docker run -e CI=true edwardyhuang/docker-react npm run test -- --coverage

deploy:
  provider: elasticbeanstalk
  region: "ap-southwest-1"
  app: "docker-react"
  env: "Dockerreact-env"
  bucket_name: "elasticbeanstalk-ap-southeast-1-878422455948"
  bucket_path: "docker-react"
  on:
    branch: master
  access_key_id: $AWS_ACCESS_KEY
  secret_access_key: $AWS_SECRET_KEY
